export interface Region {
  provinsi: string;
  kota: string[];
}

export const indonesiaRegions: Region[] = [
  { provinsi: "Aceh", kota: ["Kota Banda Aceh","Kota Sabang","Kota Langsa","Kota Lhokseumawe","Kota Subulussalam","Kab. Aceh Besar","Kab. Pidie","Kab. Pidie Jaya","Kab. Bireuen","Kab. Aceh Utara","Kab. Aceh Timur","Kab. Aceh Tamiang","Kab. Aceh Jaya","Kab. Aceh Barat","Kab. Nagan Raya","Kab. Aceh Barat Daya","Kab. Aceh Selatan","Kab. Aceh Singkil","Kab. Simeulue","Kab. Aceh Tengah","Kab. Bener Meriah","Kab. Gayo Lues"] },
  { provinsi: "Sumatera Utara", kota: ["Kota Medan","Kota Binjai","Kota Tebing Tinggi","Kota Pematangsiantar","Kota Tanjungbalai","Kota Sibolga","Kota Padangsidimpuan","Kota Gunungsitoli","Kab. Deli Serdang","Kab. Langkat","Kab. Karo","Kab. Simalungun","Kab. Asahan","Kab. Labuhanbatu","Kab. Tapanuli Utara","Kab. Tapanuli Tengah","Kab. Tapanuli Selatan","Kab. Mandailing Natal","Kab. Nias","Kab. Dairi","Kab. Samosir","Kab. Toba","Kab. Batubara","Kab. Serdang Bedagai"] },
  { provinsi: "Sumatera Barat", kota: ["Kota Padang","Kota Bukittinggi","Kota Padang Panjang","Kota Payakumbuh","Kota Sawahlunto","Kota Solok","Kota Pariaman","Kab. Agam","Kab. Dharmasraya","Kab. Kepulauan Mentawai","Kab. Lima Puluh Kota","Kab. Padang Pariaman","Kab. Pasaman","Kab. Pasaman Barat","Kab. Pesisir Selatan","Kab. Sijunjung","Kab. Solok","Kab. Solok Selatan","Kab. Tanah Datar"] },
  { provinsi: "Riau", kota: ["Kota Pekanbaru","Kota Dumai","Kab. Bengkalis","Kab. Indragiri Hilir","Kab. Indragiri Hulu","Kab. Kampar","Kab. Kepulauan Meranti","Kab. Kuantan Singingi","Kab. Pelalawan","Kab. Rokan Hilir","Kab. Rokan Hulu","Kab. Siak"] },
  { provinsi: "Kepulauan Riau", kota: ["Kota Tanjungpinang","Kota Batam","Kab. Bintan","Kab. Karimun","Kab. Kepulauan Anambas","Kab. Lingga","Kab. Natuna"] },
  { provinsi: "Jambi", kota: ["Kota Jambi","Kota Sungai Penuh","Kab. Batanghari","Kab. Bungo","Kab. Kerinci","Kab. Merangin","Kab. Muaro Jambi","Kab. Sarolangun","Kab. Tanjung Jabung Barat","Kab. Tanjung Jabung Timur","Kab. Tebo"] },
  { provinsi: "Sumatera Selatan", kota: ["Kota Palembang","Kota Lubuklinggau","Kota Pagaralam","Kota Prabumulih","Kab. Banyuasin","Kab. Empat Lawang","Kab. Lahat","Kab. Muara Enim","Kab. Musi Banyuasin","Kab. Musi Rawas","Kab. Ogan Ilir","Kab. Ogan Komering Ilir","Kab. Ogan Komering Ulu","Kab. OKU Selatan","Kab. OKU Timur"] },
  { provinsi: "Bangka Belitung", kota: ["Kota Pangkalpinang","Kab. Bangka","Kab. Bangka Barat","Kab. Bangka Selatan","Kab. Bangka Tengah","Kab. Belitung","Kab. Belitung Timur"] },
  { provinsi: "Bengkulu", kota: ["Kota Bengkulu","Kab. Bengkulu Selatan","Kab. Bengkulu Tengah","Kab. Bengkulu Utara","Kab. Kaur","Kab. Kepahiang","Kab. Lebong","Kab. Mukomuko","Kab. Rejang Lebong","Kab. Seluma"] },
  { provinsi: "Lampung", kota: ["Kota Bandar Lampung","Kota Metro","Kab. Lampung Barat","Kab. Lampung Selatan","Kab. Lampung Tengah","Kab. Lampung Timur","Kab. Lampung Utara","Kab. Mesuji","Kab. Pesawaran","Kab. Pesisir Barat","Kab. Pringsewu","Kab. Tanggamus","Kab. Tulang Bawang","Kab. Way Kanan"] },
  { provinsi: "DKI Jakarta", kota: ["Kota Jakarta Pusat","Kota Jakarta Utara","Kota Jakarta Barat","Kota Jakarta Selatan","Kota Jakarta Timur","Kab. Kepulauan Seribu"] },
  { provinsi: "Jawa Barat", kota: ["Kota Bandung","Kota Bekasi","Kota Bogor","Kota Cimahi","Kota Cirebon","Kota Depok","Kota Sukabumi","Kota Tasikmalaya","Kota Banjar","Kab. Bandung","Kab. Bandung Barat","Kab. Bekasi","Kab. Bogor","Kab. Ciamis","Kab. Cianjur","Kab. Cirebon","Kab. Garut","Kab. Indramayu","Kab. Karawang","Kab. Kuningan","Kab. Majalengka","Kab. Pangandaran","Kab. Purwakarta","Kab. Subang","Kab. Sukabumi","Kab. Sumedang","Kab. Tasikmalaya"] },
  { provinsi: "Banten", kota: ["Kota Cilegon","Kota Serang","Kota Tangerang","Kota Tangerang Selatan","Kab. Lebak","Kab. Pandeglang","Kab. Serang","Kab. Tangerang"] },
  { provinsi: "DI Yogyakarta", kota: ["Kota Yogyakarta","Kab. Bantul","Kab. Gunungkidul","Kab. Kulon Progo","Kab. Sleman"] },
  { provinsi: "Jawa Tengah", kota: ["Kota Semarang","Kota Solo","Kota Salatiga","Kota Magelang","Kota Pekalongan","Kota Tegal","Kab. Banjarnegara","Kab. Banyumas","Kab. Batang","Kab. Blora","Kab. Boyolali","Kab. Brebes","Kab. Cilacap","Kab. Demak","Kab. Grobogan","Kab. Jepara","Kab. Karanganyar","Kab. Kebumen","Kab. Kendal","Kab. Klaten","Kab. Kudus","Kab. Magelang","Kab. Pati","Kab. Pekalongan","Kab. Pemalang","Kab. Purbalingga","Kab. Purworejo","Kab. Rembang","Kab. Semarang","Kab. Sragen","Kab. Sukoharjo","Kab. Tegal","Kab. Temanggung","Kab. Wonogiri","Kab. Wonosobo"] },
  { provinsi: "Jawa Timur", kota: ["Kota Surabaya","Kota Malang","Kota Batu","Kota Blitar","Kota Kediri","Kota Madiun","Kota Mojokerto","Kota Pasuruan","Kota Probolinggo","Kab. Bangkalan","Kab. Banyuwangi","Kab. Blitar","Kab. Bojonegoro","Kab. Bondowoso","Kab. Gresik","Kab. Jember","Kab. Jombang","Kab. Kediri","Kab. Lamongan","Kab. Lumajang","Kab. Madiun","Kab. Magetan","Kab. Malang","Kab. Mojokerto","Kab. Nganjuk","Kab. Ngawi","Kab. Pacitan","Kab. Pamekasan","Kab. Pasuruan","Kab. Ponorogo","Kab. Probolinggo","Kab. Sampang","Kab. Sidoarjo","Kab. Situbondo","Kab. Sumenep","Kab. Trenggalek","Kab. Tuban","Kab. Tulungagung"] },
  { provinsi: "Bali", kota: ["Kota Denpasar","Kab. Badung","Kab. Bangli","Kab. Buleleng","Kab. Gianyar","Kab. Jembrana","Kab. Karangasem","Kab. Klungkung","Kab. Tabanan"] },
  { provinsi: "Nusa Tenggara Barat", kota: ["Kota Mataram","Kota Bima","Kab. Bima","Kab. Dompu","Kab. Lombok Barat","Kab. Lombok Tengah","Kab. Lombok Timur","Kab. Lombok Utara","Kab. Sumbawa","Kab. Sumbawa Barat"] },
  { provinsi: "Nusa Tenggara Timur", kota: ["Kota Kupang","Kab. Alor","Kab. Belu","Kab. Ende","Kab. Flores Timur","Kab. Kupang","Kab. Lembata","Kab. Malaka","Kab. Manggarai","Kab. Manggarai Barat","Kab. Manggarai Timur","Kab. Nagekeo","Kab. Ngada","Kab. Rote Ndao","Kab. Sabu Raijua","Kab. Sikka","Kab. Sumba Barat","Kab. Sumba Barat Daya","Kab. Sumba Tengah","Kab. Sumba Timur","Kab. Timor Tengah Selatan","Kab. Timor Tengah Utara"] },
  { provinsi: "Kalimantan Barat", kota: ["Kota Pontianak","Kota Singkawang","Kab. Bengkayang","Kab. Kapuas Hulu","Kab. Kayong Utara","Kab. Ketapang","Kab. Kubu Raya","Kab. Landak","Kab. Melawi","Kab. Mempawah","Kab. Sambas","Kab. Sanggau","Kab. Sekadau","Kab. Sintang"] },
  { provinsi: "Kalimantan Tengah", kota: ["Kota Palangka Raya","Kab. Barito Selatan","Kab. Barito Timur","Kab. Barito Utara","Kab. Gunung Mas","Kab. Kapuas","Kab. Katingan","Kab. Kotawaringin Barat","Kab. Kotawaringin Timur","Kab. Lamandau","Kab. Murung Raya","Kab. Pulang Pisau","Kab. Seruyan","Kab. Sukamara"] },
  { provinsi: "Kalimantan Selatan", kota: ["Kota Banjarmasin","Kota Banjarbaru","Kab. Balangan","Kab. Banjar","Kab. Barito Kuala","Kab. Hulu Sungai Selatan","Kab. Hulu Sungai Tengah","Kab. Hulu Sungai Utara","Kab. Kotabaru","Kab. Tabalong","Kab. Tanah Bumbu","Kab. Tanah Laut","Kab. Tapin"] },
  { provinsi: "Kalimantan Timur", kota: ["Kota Samarinda","Kota Balikpapan","Kota Bontang","Kab. Berau","Kab. Kutai Barat","Kab. Kutai Kartanegara","Kab. Kutai Timur","Kab. Mahakam Ulu","Kab. Paser","Kab. Penajam Paser Utara"] },
  { provinsi: "Kalimantan Utara", kota: ["Kota Tarakan","Kab. Bulungan","Kab. Malinau","Kab. Nunukan","Kab. Tana Tidung"] },
  { provinsi: "Sulawesi Utara", kota: ["Kota Manado","Kota Bitung","Kota Kotamobagu","Kota Tomohon","Kab. Bolaang Mongondow","Kab. Kepulauan Sangihe","Kab. Kepulauan Talaud","Kab. Minahasa","Kab. Minahasa Selatan","Kab. Minahasa Tenggara","Kab. Minahasa Utara"] },
  { provinsi: "Gorontalo", kota: ["Kota Gorontalo","Kab. Boalemo","Kab. Bone Bolango","Kab. Gorontalo","Kab. Gorontalo Utara","Kab. Pohuwato"] },
  { provinsi: "Sulawesi Tengah", kota: ["Kota Palu","Kab. Banggai","Kab. Banggai Kepulauan","Kab. Banggai Laut","Kab. Buol","Kab. Donggala","Kab. Morowali","Kab. Morowali Utara","Kab. Parigi Moutong","Kab. Poso","Kab. Sigi","Kab. Tojo Una-Una","Kab. Toli-Toli"] },
  { provinsi: "Sulawesi Selatan", kota: ["Kota Makassar","Kota Palopo","Kota Parepare","Kab. Bantaeng","Kab. Barru","Kab. Bone","Kab. Bulukumba","Kab. Enrekang","Kab. Gowa","Kab. Jeneponto","Kab. Kepulauan Selayar","Kab. Luwu","Kab. Luwu Timur","Kab. Luwu Utara","Kab. Maros","Kab. Pangkajene dan Kepulauan","Kab. Pinrang","Kab. Sidenreng Rappang","Kab. Sinjai","Kab. Soppeng","Kab. Takalar","Kab. Tana Toraja","Kab. Toraja Utara","Kab. Wajo"] },
  { provinsi: "Sulawesi Barat", kota: ["Kab. Majene","Kab. Mamasa","Kab. Mamuju","Kab. Mamuju Tengah","Kab. Pasangkayu","Kab. Polewali Mandar"] },
  { provinsi: "Sulawesi Tenggara", kota: ["Kota Bau-Bau","Kota Kendari","Kab. Bombana","Kab. Buton","Kab. Buton Selatan","Kab. Buton Tengah","Kab. Buton Utara","Kab. Kolaka","Kab. Kolaka Timur","Kab. Kolaka Utara","Kab. Konawe","Kab. Konawe Kepulauan","Kab. Konawe Selatan","Kab. Konawe Utara","Kab. Muna","Kab. Muna Barat","Kab. Wakatobi"] },
  { provinsi: "Maluku", kota: ["Kota Ambon","Kota Tual","Kab. Buru","Kab. Buru Selatan","Kab. Kepulauan Aru","Kab. Maluku Barat Daya","Kab. Maluku Tengah","Kab. Maluku Tenggara","Kab. Seram Bagian Barat","Kab. Seram Bagian Timur"] },
  { provinsi: "Maluku Utara", kota: ["Kota Ternate","Kota Tidore Kepulauan","Kab. Halmahera Barat","Kab. Halmahera Selatan","Kab. Halmahera Tengah","Kab. Halmahera Timur","Kab. Halmahera Utara","Kab. Kepulauan Sula","Kab. Pulau Morotai","Kab. Pulau Taliabu"] },
  { provinsi: "Papua Barat", kota: ["Kota Sorong","Kab. Fakfak","Kab. Kaimana","Kab. Maybrat","Kab. Raja Ampat","Kab. Sorong","Kab. Sorong Selatan","Kab. Tambrauw","Kab. Teluk Bintuni","Kab. Teluk Wondama"] },
  { provinsi: "Papua Barat Daya", kota: ["Kota Sorong","Kab. Maybrat","Kab. Raja Ampat","Kab. Sorong Selatan","Kab. Tambrauw"] },
  { provinsi: "Papua", kota: ["Kota Jayapura","Kab. Asmat","Kab. Biak Numfor","Kab. Boven Digoel","Kab. Deiyai","Kab. Dogiyai","Kab. Intan Jaya","Kab. Jayapura","Kab. Jayawijaya","Kab. Keerom","Kab. Kepulauan Yapen","Kab. Lanny Jaya","Kab. Mamberamo Raya","Kab. Mamberamo Tengah","Kab. Mappi","Kab. Merauke","Kab. Mimika","Kab. Nabire","Kab. Nduga","Kab. Paniai","Kab. Pegunungan Bintang","Kab. Puncak","Kab. Puncak Jaya","Kab. Sarmi","Kab. Supiori","Kab. Tolikara","Kab. Waropen","Kab. Yahukimo","Kab. Yalimo"] },
  { provinsi: "Papua Tengah", kota: ["Kab. Deiyai","Kab. Dogiyai","Kab. Intan Jaya","Kab. Mimika","Kab. Nabire","Kab. Paniai","Kab. Puncak","Kab. Puncak Jaya"] },
  { provinsi: "Papua Pegunungan", kota: ["Kab. Jayawijaya","Kab. Lanny Jaya","Kab. Mamberamo Tengah","Kab. Nduga","Kab. Pegunungan Bintang","Kab. Tolikara","Kab. Yahukimo","Kab. Yalimo"] },
  { provinsi: "Papua Selatan", kota: ["Kab. Asmat","Kab. Boven Digoel","Kab. Mappi","Kab. Merauke"] },
];

export const provinsiList = indonesiaRegions.map((r) => r.provinsi);

export function getKotaByProvinsi(provinsi: string): string[] {
  return indonesiaRegions.find((r) => r.provinsi === provinsi)?.kota ?? [];
}
